#!/bin/bash
#for i in $(find . -maxdepth 1 -type d | tail -7);
#do
#        cd $i
#	touch $count\_Ejemplo_$(date +'%d-%m-%Y %H:%M')
#        count=$(expr $count + 1)
#        cd ..
#done


echo -n "Ingrese el nombre del archivo: " 
read nombre
echo -n "Ingrese la extensión: "
read ext 
#idactual=$(cat idregister | wc -l)
id=$(find ./ -type f | wc -l)
#idnuevo=$(expr $idactual + 1)
touch $id\_$nombre_$(date +'%d-%m-%Y-%H:%M').$ext

echo -e "\nArchivo creado con éxito en: " $(pwd)

