#!/bin/bash
#for i in $(find . -maxdepth 1 -type d | tail -7);
#do
#        cd $i
#	touch $count\_Ejemplo_$(date +'%d-%m-%Y %H:%M')
#        count=$(expr $count + 1)
#        cd ..
#done


echo -n "Ingrese el nombre del archivo: " 
read nombre
echo -n "Ingrese la extensión: "
read ext 
id=$(echo $(find ../../docs/ -type f | wc -l))

fecha=$(date +'%d-%m-%Y %H-%M')
nombredef=$id\_$nombre\_$fecha\.$ext
IFS='
'
touch $nombredef
echo -e "\nArchivo creado con éxito en: " $(pwd)

